products = [
    {
      '_id': '1',
      'name': 'Monitor de Áudio, Edifier, R1000T4 preta',
      'url': 'http://localhost:8000/images/R1000T4.jpg',
      'image': '/images/R1000T4.jpg',
      'description':
        'Monitor de Áudio 24W RMS R1000T4 EDIFIER 2 Bivolt - madeira A EDIFIER R1000T4 possui atualização tecnológica com amplificador melhorado de classe-D, sua potência de 24W RMS fara que aproveite ao máximo o seu som. Acústica Surpreendente Material com fibra de Madeira 100% (MDF), este monitor de áudio é construído para resistir à ressonância. Para ser usado em home studio, em casa ou no escritório, esta é a opção perfeita com o melhor custo benefício do mercado nacional. Uso Semiprofissional Apesar de ser um produto dedicado aqueles que estão a procura dos tons mais limpos e nítidos, a R1000T4 não se direciona apenas a esse grupo. Seja você um entusiasta de jogos ou simplesmente quer dar ainda mais qualidade para os conteúdos multimídia que você reproduz no seu computador, celular ou tablet, esse monitor irá cair como uma luva. Surpreenda-se com os resultados e viva experiências com ainda mais emoção. Som Genuíno e Equilibrado Se você está iniciando seus primeiros projetos com edição de áudio, essa é uma ótima e barata opção de dar os próximos passos. A diferença da Edifier R1000T4 das demais caixas presentes no mercado é que não atua modificando as frequências do áudio, ou seja, é flat o que significa que ele vem com todas as frequências equilibradas, não tem equalização. O que ele reproduzir vai estar o mais próximo possível do gravado, assim você vai ter uma referência melhor para se basear ao equalizar os instrumentos. Um toque de estilo Apresentando drivers de graves de 4″ e drivers de tweeter de diafragma de seda de ¾”, o monitor de áudio EDIFIER R1000T4 é projetado para oferecer som com emoções e detalhes. E o par de drivers de graves dourados adicionam um toque de estilo ao seu ambiente. Dupla Entrada RCA Para uma experiência de áudio personalizada, você encontrará os controles de ajuste de graves e volume na parte de trás deste monitor de áudio. A EDIFIER R1000T4 também possui duas portas de entrada de linha estéreo, com aprimoramento dinâmicos de agudos na porta "A". DADOS TÉCNICOS - Potencia: 24Watts RMS (12Wx2) - Agudos: 1, 2”. - Graves: 4”. - Proteção Magnética: Sim - S/ N Ratio: > 85 dB - Distorção: 0.5% - Frequência response: 75Hz 18KHZ (+/-9dB) - Nível de Entrada: PC: 700mV 50mV AUX: 550mV 50mV - Bivolt - impedância: 4ohm ITENS INCLUSOS 1-Coluna Ativa 1-Coluna Passiva 1-Cabo de ligação das colunas 1-Cabo de ligação de áudio de p2(3.5 mm) para RCA duplo 1-Cabo de áudio (RCA – RCA estéreo) 1-Manual.',
      'brand': 'Edifier',
      'category': 'Electronics',
      'price': 779.99,
      'countInStock': 5,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Smart TV LED 50" 4K UHD Samsung 50BU8000',
      'url': 'http://localhost:8000/images/50BU8000.jpg',
      'image': '/images/50BU8000.jpg',
      'description':
        'Samsung Smart TV 50 polegadas Crystal UHD 4K BU8000 2022, Painel Dynamic Crystal Color, Design slim, Tela sem limites, Visual Livre de Cabos, Alexa built in, Controle Remoto Único.',
      'brand': 'Samsung',
      'category': 'Electronics',
      'price': 2510.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Teclado mecânico Keychron K4 wireless',
      'url': 'http://localhost:8000/images/keychronk4.jpg',
      'image': '/images/keychronk4.jpg',
      'description':
        'Keychron K4 Teclado mecânico para jogos sem fio Bluetooth/USB com fio, compacto, 100 teclas, RGB LED, retroiluminado, Gateron G Pro Brown Switch N-Key, moldura de alumínio para Mac Windows, versão 2',
      'brand': 'Keychrons',
      'category': 'Electronics',
      'price': 849.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'PlayStation®5 + God of War Ragnarök',
      'url': 'http://localhost:8000/images/ps5.jpg',
      'image': '/images/ps5.jpg',
      'description':
        'Experimente o carregamento extremamente rápido do SSD de ultra-velocidade, uma imersão mais profunda com suporte à resposta tátil, gatilhos adaptáveis e áudio 3D. Além de uma geração totalmente nova de jogos incríveis. O console PS5 oferece novas possibilidades de jogabilidade que você nunca imaginou.',
      'brand': 'Sony',
      'category': 'Electronics',
      'price': 4000.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Mouse Laser Profissional sem Fio MX Master 3 - Logitech',
      'url': 'http://localhost:8000/images/mxmaster3.jpg',
      'image': '/images/mxmaster3.jpg',
      'description':
        'O MX Master 3 oferece precisão instantânea e potencial infinito. Projetado para designers e desenvolvido para desenvolvedores, é o nosso mouse da Master Series mais avançado até agora. A roda MagSpeed eletromagnética quase completamente silenciosa oferece até 90% mais velocidade e 87% mais precisão. As personalizações de botões específicas do aplicativo aceleram seu fluxo de trabalho nos aplicativos que você mais usa. Sensor Darkfield de 4000 DPI significa que você pode rastrear praticamente em qualquer lugar - até mesmo em vidro. É cinco vezes mais rápido e mais preciso do que um mouse básico. Sua mão descansa perfeitamente na forma esculpida e o Flow permite que você trabalhe em vários computadores e sistemas operacionais - transferindo arquivos, imagens e pastas em um fluxo de trabalho perfeito.',
      'brand': 'Logitech',
      'category': 'Electronics',
      'price': 750.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    }
  ]
